### PR TITLE
closed loop mega merge

### PR DESCRIPTION
**Pull request by rueberger**

### CODE REVIEW

**Comment by minseungchoi** [comment]
Andrew, I don't think we're ready to merge the closedloop branch bc it's on flystim 1.0, while master is on 2.0. I want to hold off on merging things to 2.0 until we're done with getting closed loop in a ready state. What do you think?

**Comment by rueberger** [comment]
sounds good to me, sorry got a bit overzealous. what's new in flystim 2.0 @mhturner?

**Comment by mhturner** [comment]
If your plan is to use flystim2.0 for your closed loop experiments I might suggest merging sooner rather than later. Not into master but into an updated closed loop 2.0 branch that we can eventually merge into master. A lot of things changed in flystim 2.0 and two will only get more different. I don't have much experience doing big merges like this between two quite different repos but I don't know if it will be easy. That said - it's your party so do what you feel. Flystim2.0 changes the way all stimuli are rendered, adds/removes some stimuli, refactors how stimuli are parameterized (all by a little, some by a lot). Briefly looking at your branch you might not be in too much trouble merging I think. Merging later might be totally fine but I would hate for you guys to put a bunch of work into something before figuring out that a different solution is needed for flystim2.0 or whatever. Either way happy to help with any problems you run into any way I can.

**Comment by minseungchoi** [comment]
@mhturner Great suggestions! I think we'll merge as soon as the "low-level" mechanics of closed-loop are done. When we get to coding up the stimulus, we'll use 2.0.

**Comment by minseungchoi** [comment]
New branch flystim2.0_closedloop has been created.

**Pull request closed without merging**
